---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cm-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-configmaps
rules:
- verbs:
  - watch
  - get
  - list
  apiGroups:
  - ""
  resources:
  - configmaps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-config-maps-to-cm-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-configmaps
subjects:
- kind: ServiceAccount
  name: cm-reader 
---
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  shareProcessNamespace: true
  serviceAccountName: cm-reader
  containers:
  - name: payload
    image: quay.io/lkrejci/signal-handler  
    imagePullPolicy: Always
    volumeMounts:
    - name: configs
      mountPath: /configs
  - name: bumper
    image: quay.io/lkrejci/cm-bump
    imagePullPolicy: Always
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
    env:
    - name: CM_DIR
      value: /configs
    - name: CM_LABELS
      value: 'config-bump==reload'
    - name: CM_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: CM_PROC_CMD
      value: signal-hand.*
    - name: CM_PROC_SIGNAL
      value: SIGHUP
      #    - name: CM_LOG
      #value: info,cm_bump=trace,kube=warn
    volumeMounts:
    - name: configs
      mountPath: /configs
  volumes:
  - name: configs
    emptyDir: {}

